variable "db_name" {
  type        = string
  description = "The name of the database to be created."
}

variable "location" {
  type        = string
  description = "The location/region where the database and server are created. Changing this forces a new resource to be created."
}

variable "sql_admin_username" {
  type        = string
  description = "The administrator username of the SQL Server."
}

variable "sql_password" {
  type        = string
  description = "The administrator password of the SQL Server."
  sensitive   = true
}

variable "collation" {
  type        = string
  default     = "SQL_Latin1_General_CP1_CI_AS"
  description = "The collation for the database. Default is SQL_Latin1_General_CP1_CI_AS"
}

variable "db_edition" {
  type        = string
  default     = "Basic"
  description = "The edition of the database to be created."
}

variable "end_ip_address" {
  type        = string
  default     = "0.0.0.0"
  description = "Defines the end IP address used in your database firewall rule."
}

variable "resource_group_name" {
  type        = string
  default     = "myapp-rg"
  description = "Default resource group name that the database will be created in."
}

variable "server_version" {
  type        = string
  default     = "12.0"
  description = "The version for the database server. Valid values are: 2.0 (for v11 server) and 12.0 (for v12 server)."
}

variable "service_objective_name" {
  type        = string
  default     = "Basic"
  description = "The performance level for the database. For the list of acceptable values, see https://docs.microsoft.com/en-gb/azure/sql-database/sql-database-service-tiers. Default is Basic."
}

variable "start_ip_address" {
  type        = string
  default     = "0.0.0.0"
  description = "Defines the start IP address used in your database firewall rule."
}

variable "tags" {
  type = map(string)
  default = {
    tag1 = ""
    tag2 = ""
  }
  description = "The tags to associate with your network and subnets."
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_enabled" {
  type        = bool
  default     = false
  description = "Whether enable tracing tags that generated by BridgeCrew Yor."
  nullable    = false
}

# tflint-ignore: terraform_unused_declarations
variable "tracing_tags_prefix" {
  type        = string
  default     = "avm_"
  description = "Default prefix for generated tracing tags"
  nullable    = false
}
